selected_ids = [
    "sphinx-doc__sphinx-9258",
    "sympy__sympy-13551",
    "sphinx-doc__sphinx-9698",
    "sphinx-doc__sphinx-8269",
    "sphinx-doc__sphinx-8638",
    "sphinx-doc__sphinx-9320",
    "scikit-learn__scikit-learn-15100",
    "sympy__sympy-13480",
    "sphinx-doc__sphinx-9591",
    "sympy__sympy-13877",
    "sympy__sympy-24539",
    "sphinx-doc__sphinx-10614",
    "sympy__sympy-13031",
    "sympy__sympy-24562",
    "sphinx-doc__sphinx-8548",
    "sympy__sympy-22714",
    "sphinx-doc__sphinx-8265",
    "sphinx-doc__sphinx-8475",
    "sphinx-doc__sphinx-9711",
    "sympy__sympy-23824",
    "sympy__sympy-18189",
    "sympy__sympy-23262",
    "scikit-learn__scikit-learn-14710",
    "scikit-learn__scikit-learn-26194",
    "sphinx-doc__sphinx-10466",
    "sympy__sympy-12419",
    "sympy__sympy-13372",
    "sphinx-doc__sphinx-8551",
    "scikit-learn__scikit-learn-9288",
    "scikit-learn__scikit-learn-14629",
    "sympy__sympy-21596",
    "sympy__sympy-13615",
    "sympy__sympy-13091",
    "sphinx-doc__sphinx-10323",
    "sympy__sympy-14711",
    "sympy__sympy-16450",
    "sympy__sympy-17318",
    "sympy__sympy-12096",
    "sympy__sympy-13757",
]
