### 50 hardest dev set: https://cerebras.slack.com/archives/C07GNS2FZAT/p1760343853553379?thread_ts=1760099722.882939&cid=C07GNS2FZAT

selected_ids = [
    "pvlib__pvlib-python-1666",
    "pvlib__pvlib-python-1478",
    "pylint-dev__astroid-2015",
    "pyvista__pyvista-432",
    "pyvista__pyvista-3675",
    "sqlfluff__sqlfluff-880",
    "sqlfluff__sqlfluff-891",
    "marshmallow-code__marshmallow-2123",
    "pvlib__pvlib-python-1623",
    "pvlib__pvlib-python-1176",
    "pvlib__pvlib-python-1469",
    "pvlib__pvlib-python-1033",
    "pydicom__pydicom-916",
    "pydicom__pydicom-1236",
    "pvlib__pvlib-python-718",
    "pvlib__pvlib-python-1053",
    "pvlib__pvlib-python-1518",
    "pylint-dev__astroid-1741",
    "pylint-dev__astroid-1030",
    "pylint-dev__astroid-2219",
    "pyvista__pyvista-4226",
    "pyvista__pyvista-3750",
    "pyvista__pyvista-4225",
    "pydicom__pydicom-1241",
    "pydicom__pydicom-1017",
    "pydicom__pydicom-1048",
    "pydicom__pydicom-1720",
    "pydicom__pydicom-1334",
    "pydicom__pydicom-997",
    "marshmallow-code__marshmallow-1229",
    "pvlib__pvlib-python-823",
    "pvlib__pvlib-python-1186",
    "pvlib__pvlib-python-1764",
    "pvlib__pvlib-python-1682",
    "pvlib__pvlib-python-1832",
    "pvlib__pvlib-python-1089",
    "pylint-dev__astroid-2240",
    "pylint-dev__astroid-1417",
    "pylint-dev__astroid-984",
    "pylint-dev__astroid-1092",
    "pylint-dev__astroid-983",
    "pydicom__pydicom-995",
    "pydicom__pydicom-897",
    "pydicom__pydicom-1674",
    "pydicom__pydicom-1375",
    "pvlib__pvlib-python-807",
    "pvlib__pvlib-python-1048",
    "pvlib__pvlib-python-1181",
    "pvlib__pvlib-python-1480",
    "pvlib__pvlib-python-763",
]
